// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzrmohjyuixifussumif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6cm1vaGp5dWl4aWZ1c3N1bWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NTkyODgsImV4cCI6MjA3NTIzNTI4OH0.yAzoo6L53i278toe0zZ0Bx_hIihjXXHtBlWWADmK5hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});